if (GetLocale() =="zhCN") then
	SPELL_TIMER_TITLE = "法术计时器";
	SPELL_TIMER_TEXT_OPTION_SLIDER = "你可以在原有法术的持续时间上再额外增加一段时间，拖动该滑动条来调整该时间。";
	SPELL_TIMER_SHOW_NAME = "显示魔法名称";
	SPELL_TIMER_SHOW_PROGRESS = "显示进度条";

	SPELL_TIMER_POISON = "药膏";
	SPELL_TIMER_VENOMOUS = "毒蛇";

	SPELL_TIMER_TRAP_PATTERN1 = "(.-)效果";
	SPELL_TIMER_TRAP_PATTERN2 = "(.-)光环";

	SPELL_TIMER_TOTEM_PATTERN = "图腾";

	SPELL_TIMER_TOTEM_TIP = "你可以使用鼠标右键取消该图腾。"

	SPELL_TIMER_UNITFRAME_TOOLTIP = "点击小锁解开/锁定窗口";

	SPELLTIMER_HOUR_WORD = "小时";
	SPELLTIMER_MINUTE_WORD = "分钟";
	SPELLTIMER_SECOND_WORD = "秒";

	SPELLTIMER_COOLDOWN_INFO = "%s的剩余时间还有%s。";

	SPELL_TIMER_PATTERN_TABLE = {};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARLOCK] = {};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARLOCK]["恐惧"] = {"debuff", nil, {["unique"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARLOCK]["献祭"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARLOCK]["放逐术"] = {"debuff", nil, {["unique"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARLOCK]["腐蚀术"] = {"debuff", {"腐蚀之种"}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARLOCK]["腐蚀之种"] = {"debuff", {"腐蚀术"}, {["unique"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARLOCK]["厄运诅咒"] = {"debuff", {"痛苦诅咒", "元素诅咒", "虚弱诅咒", "语言诅咒", "疲劳诅咒"}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARLOCK]["痛苦诅咒"] = {"debuff", {"厄运诅咒", "元素诅咒", "虚弱诅咒", "语言诅咒", "疲劳诅咒"}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARLOCK]["元素诅咒"] = {"debuff", {"厄运诅咒", "痛苦诅咒", "虚弱诅咒", "语言诅咒", "疲劳诅咒"}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARLOCK]["虚弱诅咒"] = {"debuff", {"厄运诅咒", "痛苦诅咒", "元素诅咒", "语言诅咒", "疲劳诅咒"}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARLOCK]["语言诅咒"] = {"debuff", {"厄运诅咒", "痛苦诅咒", "元素诅咒", "虚弱诅咒", "疲劳诅咒"}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARLOCK]["疲劳诅咒"] = {"debuff", {"厄运诅咒", "痛苦诅咒", "元素诅咒", "虚弱诅咒", "语言诅咒"}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARLOCK]["死亡缠绕"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARLOCK]["恐惧嚎叫"] = {"持续%t", nil, {["live"] = 1,["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARLOCK]["暗影烈焰"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARLOCK]["奴役恶魔"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARLOCK]["痛苦无常"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARLOCK]["诱惑"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARLOCK]["鬼影缠身"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARLOCK]["暗影防护结界"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARLOCK]["恶魔变形"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARLOCK]["挑战嚎叫"] = {"持续%t", nil, {["live"] = 1,["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARLOCK]["暗影之怒"] = {"debuff"};

	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_ROGUE] = {};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_ROGUE][SPELL_TIMER_POISON] = {};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_ROGUE]["凿击"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_ROGUE]["锁喉"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_ROGUE]["闷棍"] = {"debuff", nil, {["live"] = 1, ["unique"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_ROGUE]["破甲"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_ROGUE]["偷袭"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_ROGUE]["致盲"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_ROGUE]["割裂"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_ROGUE]["毒伤"] = {"buff" , nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_ROGUE]["切割"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_ROGUE]["脚踢"] = {"持续%t"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_ROGUE]["扰乱"] = {"持续%t", nil, {["live"] = 1,["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_ROGUE]["还击"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_ROGUE]["肾击"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_ROGUE]["血之饥渴"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_ROGUE]["暗影之舞"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_ROGUE]["冲动"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_ROGUE]["鬼魅攻击"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_ROGUE]["消失"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_ROGUE]["佯攻"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_ROGUE]["嫁祸诀窍"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_ROGUE]["疾跑"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_ROGUE]["闪避"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_ROGUE]["暗影步"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_ROGUE]["剑刃乱舞"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_ROGUE]["装死"] = {"buff", nil, {["live"] = 1, ["spell"] = {"装死 CD", 60}}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_ROGUE]["出血"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_ROGUE]["暗影斗篷"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_ROGUE]["致命投掷"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_ROGUE]["拆卸"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_ROGUE]["打劫"] = {"debuff"};

	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PRIEST] = {};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PRIEST]["暗言术：痛"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PRIEST]["沉默"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PRIEST]["心灵尖啸"] = {"持续%t", nil, {["live"] = 1,["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PRIEST]["吸血鬼之触"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PRIEST]["心灵惊骇"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PRIEST]["束缚亡灵"] = {"debuff", nil, {["unique"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PRIEST]["噬灵疫病"] = {"debuff", nil, {["unique"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PRIEST]["神圣之火"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PRIEST]["安抚心灵"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PRIEST]["星辰碎片"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PRIEST]["暗影恶魔"] = {"持续%t", nil, {["live"] = 1,["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PRIEST]["真言术：盾"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PRIEST]["愈合祷言"] = {"buff", nil, {["live"] = 1,["unique"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PRIEST]["恢复"] = {"buff", nil, {["live"] = 1,["needMana"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PRIEST]["守护之魂"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PRIEST]["能量灌注"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PRIEST]["痛苦压制"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PRIEST]["消散"] = {"buff", nil, {["live"] = 1}};

	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARRIOR] = {};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARRIOR]["断筋"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARRIOR]["撕裂"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARRIOR]["盾击"] = {"持续%t"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARRIOR]["挫志怒吼"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARRIOR]["刺耳怒吼"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARRIOR]["惩戒痛击"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARRIOR]["雷霆一击"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARRIOR]["缴械"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARRIOR]["破胆怒吼"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARRIOR]["破甲攻击"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARRIOR]["致死打击"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARRIOR]["拦截"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARRIOR]["挑战怒吼"] = {"持续%t", nil, {["live"] = 1,["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARRIOR]["法术反射"] = {"buff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARRIOR]["缴械"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARRIOR]["狂暴之怒"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARRIOR]["血性狂暴"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARRIOR]["死亡之愿"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARRIOR]["破釜沉舟"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARRIOR]["反击风暴"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARRIOR]["盾墙"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARRIOR]["鲁莽"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARRIOR]["震荡猛击"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARRIOR]["震荡波"] = {"debuff"};

	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_HUNTER] = {};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_HUNTER]["照明弹"] = {"持续%t", nil, {["live"] = 1,["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_HUNTER]["摔绊"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_HUNTER]["恐吓野兽"] = {"debuff",nil,{["unique"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_HUNTER]["猎人印记"] = {"debuff",nil, {["live"] = 1,["unique"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_HUNTER]["反击"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_HUNTER]["治疗宠物"] = {"buff", nil, {["live"] = 1,["unique"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_HUNTER]["狂野怒火"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_HUNTER]["主人的召唤"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_HUNTER]["毒蛇钉刺"] = {"debuff", {"蝰蛇钉刺", "毒蝎钉刺", "翼龙钉刺"}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_HUNTER]["蝰蛇钉刺"] = {"debuff", {"毒蛇钉刺", "毒蝎钉刺", "翼龙钉刺"}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_HUNTER]["毒蝎钉刺"] = {"debuff", {"毒蛇钉刺", "蝰蛇钉刺", "翼龙钉刺"}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_HUNTER]["翼龙钉刺"] = {"debuff", {"毒蛇钉刺", "蝰蛇钉刺", "毒蝎钉刺"}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_HUNTER]["冰冻陷阱"] = {{"SpellTimer_TrapSearchFunc", {"最多%t", "存在%t"}, "SpellTimer_TrapActiveFunc"}, nil, {["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_HUNTER]["冰霜陷阱"] = {{"SpellTimer_TrapSearchFunc", {"持续%t", "存在%t"}, "SpellTimer_TrapActiveFunc"}, nil, {["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_HUNTER]["献祭陷阱"] = {{"SpellTimer_TrapSearchFunc", {"在%t", "存在%t"}, "SpellTimer_TrapActiveFunc"}, nil, {["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_HUNTER]["爆炸陷阱"] = {{"SpellTimer_TrapSearchFunc", {"接下来的%t", "存在%t"}, "SpellTimer_TrapActiveFunc"}, nil, {["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_HUNTER]["毒蛇陷阱"] = {{"SpellTimer_TrapSearchFunc", {"将在%t", "存在%t"}, "SpellTimer_TrapActiveFunc"}, nil, {["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_HUNTER]["冰冻之箭"] = {{"SpellTimer_TrapSearchFunc", {"最多%t", "存在%t"}, "SpellTimer_TrapActiveFunc"}, nil, {["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_HUNTER]["威慑"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_HUNTER]["急速射击"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_HUNTER]["震荡射击"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_HUNTER]["瞄准射击"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_HUNTER]["沉默射击"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_HUNTER]["驱散射击"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_HUNTER]["扰乱射击"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_HUNTER]["黑箭"] = {"debuff"};

	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID] = {};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["休眠"] = {"debuff", nil, {["unique"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["月火术"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["猛击"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["挫志咆哮"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["精灵之火"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["精灵之火（野性）"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["纠缠根须"] = {"debuff", nil, {["unique"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["突袭"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["血袭"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["割裂"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["感染伤口"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["愈合"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["回春术"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["斜掠"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["野性冲锋"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["虫群"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["猛击"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["自然之力"] = {"持续%t", nil, {["live"] = 1,["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["裂伤（熊）"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["裂伤（豹）"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["割伤"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["生命绽放"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["割碎"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["野蛮咆哮"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["野性成长"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["台风"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["星辰坠落"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["自然之握"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["旋风"] = {"debuff", nil, {["unique"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["树皮术"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["激活"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["猛虎之怒"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["急奔"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["狂暴回复"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["激怒"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["生存本能"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["狂暴"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["挑战咆哮"] = {"持续%t", nil, {["live"] = 1,["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["野性冲锋 - 熊"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["野性冲锋 - 豹"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["月蚀"] = {"buff", nil, {["live"] = 1, ["spell"] = {"月蚀 CD", 30}}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["日蚀"] = {"buff", nil, {["live"] = 1, ["spell"] = {"日蚀 CD", 30}}};

	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_SHAMAN] = {};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_SHAMAN]["风暴打击"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_SHAMAN]["元素掌握"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_SHAMAN]["漩涡武器"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_SHAMAN]["激流"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_SHAMAN]["萨满之怒"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_SHAMAN]["潮汐之力"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_SHAMAN]["烈焰震击"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_SHAMAN]["冰霜震击"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_SHAMAN]["地缚术"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_SHAMAN]["大地震击"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_SHAMAN]["妖术"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_SHAMAN]["野性狼魂"] = {"持续%t", nil, {["live"] = 1,["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_SHAMAN]["嗜血"] = {"持续%t", nil, {["live"] = 1,["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_SHAMAN]["英勇"] = {"持续%t", nil, {["live"] = 1,["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_SHAMAN]["自然的守护者"] = {"buff", nil, {["live"] = 1, ["spell"] = {"自然的守护者 CD", 30}}};

	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PALADIN] = {};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PALADIN]["圣光审判"] = {"debuff", {"智慧审判", "公正审判"}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PALADIN]["智慧审判"] = {"debuff", {"圣光审判", "公正审判"}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PALADIN]["公正审判"] = {"debuff", {"圣光审判", "智慧审判"}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PALADIN]["制裁之锤"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PALADIN]["忏悔"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PALADIN]["超度邪恶"] = {"debuff", nil, {["unique"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PALADIN]["神启"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PALADIN]["光之优雅"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PALADIN]["圣光道标"] = {"buff", nil, {["live"] = 1,["unique"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PALADIN]["圣洁护盾"] = {"buff", nil, {["live"] = 1,["unique"] = 1,["needMana"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PALADIN]["复仇之怒"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PALADIN]["神圣牺牲"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PALADIN]["神圣之盾"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PALADIN]["牺牲之手"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PALADIN]["光环掌握"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PALADIN]["保护之手"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PALADIN]["圣盾术"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PALADIN]["圣佑术"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PALADIN]["拯救之手"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PALADIN]["自由之手"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PALADIN]["神圣愤怒"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PALADIN]["复仇者之盾"] = {"debuff"};

	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_MAGE] = {};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_MAGE]["变形术"] = {"debuff", nil, {["unique"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_MAGE]["减速"] = {"debuff", nil, {["unique"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_MAGE]["冰锥术"] = {"debuff", {"寒冰箭"}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_MAGE]["寒冰箭"] = {"debuff", {"冰锥术"}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_MAGE]["炎爆术"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_MAGE]["火球术"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_MAGE]["深冬之寒"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_MAGE]["冲击波"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_MAGE]["冰霜新星"] = {"持续%t", nil, {["live"] = 1,["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_MAGE]["召唤水元素"] = {"持续%t", nil, {["notarget"] = 1, ["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_MAGE]["减速术"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_MAGE]["活动炸弹"] = {"debuff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_MAGE]["强化灼烧"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_MAGE]["奥术冲击"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_MAGE]["寒冰护体"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_MAGE]["镜像"] = {"持续%t", nil, {["live"] = 1,["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_MAGE]["霜火之箭"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_MAGE]["深度冻结"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_MAGE]["龙息术"] = {"持续%t", nil, {["live"] = 1,["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_MAGE]["防护冰霜结界"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_MAGE]["防护火焰结界"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_MAGE]["法力护盾"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_MAGE]["隐形术"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_MAGE]["奥术强化"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_MAGE]["冰冷血脉"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_MAGE]["寒冰屏障"] = {"buff", nil, {["live"] = 1, ["spell"] = {"低温", 30}}};

	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DEATHKNIGHT] = {};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DEATHKNIGHT]["冰霜疫病"] = {"debuff", nil, {["unique"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DEATHKNIGHT]["血之疫病"] = {"debuff", nil, {["unique"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DEATHKNIGHT]["黑色热疫"] = {"debuff", nil, {["unique"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DEATHKNIGHT]["绞袭"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DEATHKNIGHT]["冰冷触摸"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DEATHKNIGHT]["鲜血印记"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DEATHKNIGHT]["冰封之韧"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DEATHKNIGHT]["狂乱"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DEATHKNIGHT]["吸血鬼之血"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DEATHKNIGHT]["巫妖之躯"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DEATHKNIGHT]["黑锋冰寒"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DEATHKNIGHT]["铜墙铁壁"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DEATHKNIGHT]["白骨之盾"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DEATHKNIGHT]["寒冰锁链"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DEATHKNIGHT]["饥饿之寒"] = {"持续%t", nil, {["live"] = 1,["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DEATHKNIGHT]["反魔法护罩"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DEATHKNIGHT]["召唤石像鬼"] = {"持续%t", nil, {["live"] = 1,["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DEATHKNIGHT]["反魔法领域"] = {"持续%t", nil, {["live"] = 1,["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DEATHKNIGHT]["亡者大军"] = {"buff", nil, {["live"] = 1, ["spell"] = {"食尸鬼军团", 45}}};
elseif (GetLocale() == "zhTW") then
	SPELL_TIMER_TITLE = "法術計時器";
	SPELL_TIMER_TEXT_OPTION_SLIDER = "你可以在原有的法術的持續時間上再額外增加一段時間，拖動滑動塊來調整該時間。";
	SPELL_TIMER_SHOW_NAME = "顯示魔法名稱";
	SPELL_TIMER_SHOW_PROGRESS = "顯示進度條";

	SPELL_TIMER_POISON = "毒藥";
	SPELL_TIMER_VENOMOUS = "毒蛇";

	SPELL_TIMER_TRAP_PATTERN1 = "(.-)效果";
	SPELL_TIMER_TRAP_PATTERN2 = "(.-)光環";

	SPELL_TIMER_TOTEM_PATTERN = "圖騰";

	SPELL_TIMER_TOTEM_TIP = "你可以使用滑鼠右鍵取消該圖騰。";

	SPELL_TIMER_UNITFRAME_TOOLTIP = "點擊小鎖解開/鎖定窗口";

	SPELLTIMER_HOUR_WORD = "小時";
	SPELLTIMER_MINUTE_WORD = "分鐘";
	SPELLTIMER_SECOND_WORD = "秒";

	SPELLTIMER_COOLDOWN_INFO = "%s的剩餘時間還有%s。";

	SPELL_TIMER_PATTERN_TABLE = {};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARLOCK] = {};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARLOCK]["恐懼術"] = {"debuff", nil, {["unique"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARLOCK]["獻祭"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARLOCK]["放逐術"] = {"debuff", nil, {["unique"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARLOCK]["腐蝕術"] = {"debuff", {"腐蝕種子"}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARLOCK]["腐蝕種子"] = {"debuff", {"腐蝕術"}, {["unique"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARLOCK]["末日災厄"] = {"debuff", {"痛苦災厄", "浩劫災厄"}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARLOCK]["痛苦災厄"] = {"debuff", {"末日災厄", "浩劫災厄"}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARLOCK]["浩劫災厄"] = {"debuff", {"末日災厄", "痛苦災厄"}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARLOCK]["元素詛咒"] = {"debuff", { "虛弱詛咒", "語言詛咒", "疲勞詛咒"}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARLOCK]["虛弱詛咒"] = {"debuff", { "元素詛咒", "語言詛咒", "疲勞詛咒"}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARLOCK]["語言詛咒"] = {"debuff", { "元素詛咒", "虛弱詛咒", "疲勞詛咒"}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARLOCK]["疲勞詛咒"] = {"debuff", { "元素詛咒", "虛弱詛咒", "語言詛咒"}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARLOCK]["死亡纏繞"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARLOCK]["恐懼嚎叫"] = {"持續%t", nil, {["live"] = 1,["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARLOCK]["古爾丹之手"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARLOCK]["誘惑"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARLOCK]["惡魔化身"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARLOCK]["奴役惡魔"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARLOCK]["痛苦動盪"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARLOCK]["蝕魂術"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARLOCK]["防護暗影結界"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARLOCK]["暗影之焰"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARLOCK]["暗影之怒"] = {"debuff"};

	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_ROGUE] = {};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_ROGUE][SPELL_TIMER_POISON] = {};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_ROGUE]["鑿擊"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_ROGUE]["絞喉"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_ROGUE]["悶棍"] = {"debuff", nil, {["live"] = 1, ["unique"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_ROGUE]["破甲"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_ROGUE]["偷襲"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_ROGUE]["致盲"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_ROGUE]["割裂"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_ROGUE]["揭底之擊"] = {"debuff"};--BUFF OR DEBUFF
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_ROGUE]["卸除武裝"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_ROGUE]["擲殺"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_ROGUE]["毒化"] = {"buff" , nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_ROGUE]["切割"] = {"buff" , nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_ROGUE]["疾跑"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_ROGUE]["閃避"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_ROGUE]["能量刺激"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_ROGUE]["佯攻"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_ROGUE]["養精蓄銳"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_ROGUE]["戰鬥就緒"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_ROGUE]["暗影披風"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_ROGUE]["消失"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_ROGUE]["煙霧彈"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_ROGUE]["偷天換日"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_ROGUE]["死亡謊言"] = {"buff", nil, {["live"] = 1, ["spell"] = {"死亡謊言 CD", 60}}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_ROGUE]["腳踢"] = {"持續%t"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_ROGUE]["擾亂"] = {"持續%t", nil, {["live"] = 1,["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_ROGUE]["還擊"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_ROGUE]["腎擊"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_ROGUE]["出血"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_ROGUE]["鮮血渴求"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_ROGUE]["暗影之舞"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_ROGUE]["宿怨"] = {"debuff"};

	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PRIEST] = {};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PRIEST]["暗言術:痛"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PRIEST]["沉默"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PRIEST]["心靈尖嘯"] = {"持續%t", nil, {["live"] = 1,["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PRIEST]["恢復"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PRIEST]["聖言術:寧"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PRIEST]["漸隱術"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PRIEST]["痛苦鎮壓"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PRIEST]["恩典"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PRIEST]["真言術:壁"] = {"持續%t", nil, {["live"] = 1,["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PRIEST]["注入能量"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PRIEST]["佈道"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PRIEST]["大天使"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PRIEST]["心靈烙印"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PRIEST]["暗影惡魔"] = {"持續%t", nil, {["live"] = 1,["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PRIEST]["癒合禱言"] = {"buff", nil, {["live"] = 1,["unique"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PRIEST]["守護聖靈"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PRIEST]["真言術:盾"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PRIEST]["影散"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PRIEST]["束縛不死生物"] = {"debuff", nil, {["unique"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PRIEST]["噬靈瘟疫"] = {"debuff", nil, {["unique"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PRIEST]["神聖之火"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PRIEST]["安撫心靈"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PRIEST]["心靈恐慌"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PRIEST]["吸血之觸"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PRIEST]["星辰裂片"] = {"debuff"};

	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARRIOR] = {};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARRIOR]["斷筋"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARRIOR]["撕裂"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARRIOR]["盾擊"] = {"持續%t"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARRIOR]["挫志怒吼"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARRIOR]["刺耳怒吼"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARRIOR]["懲戒痛擊"] = {"debuff"};--是否还存在
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARRIOR]["雷霆一擊"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARRIOR]["繳械"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARRIOR]["破膽怒吼"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARRIOR]["破甲攻擊"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARRIOR]["致死打擊"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARRIOR]["碎甲投擲"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARRIOR]["挑戰怒吼"] = {"持續%t", nil, {["live"] = 1,["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARRIOR]["撂倒"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARRIOR]["震盪猛擊"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARRIOR]["攔截"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARRIOR]["震懾波"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARRIOR]["反擊風暴"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARRIOR]["巨像碎擊"] = {"debuff"};--buff or debuff
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARRIOR]["狂暴之怒"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARRIOR]["破釜沉舟"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARRIOR]["狂怒恢復"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARRIOR]["橫掃攻擊"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARRIOR]["劍下亡魂"] = {"buff", nil, {["live"] = 1, ["spell"] = {"劍下亡魂 CD", 120}}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARRIOR]["魯莽"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARRIOR]["沈著殺機"] = {"buff", {"心靈之怒"}, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARRIOR]["心靈之怒"] = {"buff", {"沈著殺機"}, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARRIOR]["死亡之願"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARRIOR]["盾牌格擋"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARRIOR]["削骨斬肉"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARRIOR]["盾牆"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARRIOR]["法術反射"] = {"buff", nil, {["live"] = 1}};

	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_HUNTER] = {};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_HUNTER]["照明彈"] = {"持續%t", nil, {["live"] = 1,["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_HUNTER]["摔絆"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_HUNTER]["恐嚇野獸"] = {"debuff",nil, {["unique"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_HUNTER]["反擊"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_HUNTER]["寡婦毒液"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_HUNTER]["治療寵物"] = {"buff", nil, {["live"] = 1,["unique"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_HUNTER]["狂野怒火"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_HUNTER]["專注之火"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_HUNTER]["威懾"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_HUNTER]["主人的呼喚"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_HUNTER]["急速射擊"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_HUNTER]["沉默射擊"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_HUNTER]["獵人印記"] = {"debuff",nil, {["live"] = 1,["unique"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_HUNTER]["死亡標記"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_HUNTER]["擾亂射擊"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_HUNTER]["毒蛇釘刺"] = {"debuff", {"蝮蛇釘刺", "毒蠍釘刺", "翼龍釘刺"}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_HUNTER]["蝮蛇釘刺"] = {"debuff", {"毒蛇釘刺", "毒蠍釘刺", "翼龍釘刺"}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_HUNTER]["毒蠍釘刺"] = {"debuff", {"毒蛇釘刺", "蝮蛇釘刺", "翼龍釘刺"}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_HUNTER]["翼龍釘刺"] = {"debuff", {"毒蛇釘刺", "蝮蛇釘刺", "毒蠍釘刺"}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_HUNTER]["震盪射擊"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_HUNTER]["驅散射擊"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_HUNTER]["黑蝕箭"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_HUNTER]["冰凍陷阱"] = {{"SpellTimer_TrapSearchFunc", {"最多%t內", "陷阱可存在%t"}, "SpellTimer_TrapActiveFunc"}, nil, {["live"] = 1,["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_HUNTER]["冰霜陷阱"] = {{"SpellTimer_TrapSearchFunc", {"持續%t", "陷阱可存在%t"}, "SpellTimer_TrapActiveFunc"}, nil, {["live"] = 1,["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_HUNTER]["獻祭陷阱"] = {{"SpellTimer_TrapSearchFunc", {"在%t內", "陷阱可存在%t"}, "SpellTimer_TrapActiveFunc"}, nil, {["live"] = 1,["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_HUNTER]["爆炸陷阱"] = {{"SpellTimer_TrapSearchFunc", {"接下來的%t", "陷阱可存在%t"}, "SpellTimer_TrapActiveFunc"}, nil, {["live"] = 1,["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_HUNTER]["毒蛇陷阱"] = {{"SpellTimer_TrapSearchFunc", {"毒蛇將在%t", "陷阱可存在%t"}, "SpellTimer_TrapActiveFunc"}, nil, {["live"] = 1,["notarget"] = 1}};

	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID] = {};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["休眠"] = {"debuff", nil, {["unique"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["月火術"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["重擊"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["挫志咆哮"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["精靈之火"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["精靈之火(野性)"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["啟動"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["奔竄咆哮"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["樹皮術"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["糾纏根鬚"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["突襲"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["血襲"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["撕扯"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["感染之傷"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["挑戰咆哮"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["狂暴恢復"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["自然之握"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["荊棘術"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["癒合"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["回春術"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["狂暴"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["求生本能"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["掃擊"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["野性衝鋒"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["蟲群"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["自然之力"] = {"持續%t", nil, {["live"] = 1,["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["割碎"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["割裂"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["狂怒"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["生命之花"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["星殞術"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["傷殘術"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["突進"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["日炎術"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["痛擊"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["颱風"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["奔竄"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["野性痊癒"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["自然之賜"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["兇蠻咆哮"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["颶風術"] = {"debuff", nil, {["unique"] = 1}};

	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_SHAMAN] = {};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_SHAMAN]["風暴打擊"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_SHAMAN]["靈行者之賜"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_SHAMAN]["精通元素"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_SHAMAN]["薩滿之怒"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_SHAMAN]["氣漩武器"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_SHAMAN]["激流"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_SHAMAN]["烈焰震擊"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_SHAMAN]["冰霜震擊"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_SHAMAN]["地縛圖騰"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_SHAMAN]["妖術"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_SHAMAN]["大地震擊"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_SHAMAN]["野性之魂"] = {"持續%t", nil, {["live"] = 1,["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_SHAMAN]["元素束縛"] = {"debuff", nil, {["unique"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_SHAMAN]["嗜血術"] = {"持續%t", nil, {["live"] = 1,["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_SHAMAN]["英勇氣概"] = {"持續%t", nil, {["live"] = 1,["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_SHAMAN]["自然守護者"] = {"buff", nil, {["live"] = 1, ["spell"] = {"自然守護者 CD", 30}}};

	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PALADIN] = {};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PALADIN]["制裁之錘"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PALADIN]["懺悔"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PALADIN]["退邪術"] = {"debuff", nil, {["unique"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PALADIN]["自由聖禦"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PALADIN]["拯救聖禦"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PALADIN]["異端審問"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PALADIN]["犧牲聖禦"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PALADIN]["保護聖禦"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PALADIN]["神聖啟發"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PALADIN]["光明賜福"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PALADIN]["復仇之怒"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PALADIN]["神性祈求"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PALADIN]["聖盾術"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PALADIN]["聖佑術"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PALADIN]["精通光環"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PALADIN]["神恩術"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PALADIN]["狂熱精神"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PALADIN]["忠誠防衛者"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PALADIN]["聖光信標"] = {"buff", nil, {["live"] = 1,["unique"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PALADIN]["公正復仇"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PALADIN]["神聖憤怒"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PALADIN]["神性守護"] = {"持續%t", nil, {["live"] = 1,["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PALADIN]["遠古諸王守護者"] = {"持續%t", nil, {["live"] = 1,["notarget"] = 1}};

	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_MAGE] = {};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_MAGE]["變形術"] = {"debuff", nil, {["unique"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_MAGE]["冰錐術"] = {"debuff", {"寒冰箭"}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_MAGE]["寒冰箭"] = {"debuff", {"冰錐術"}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_MAGE]["炎爆術"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_MAGE]["霜火箭"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_MAGE]["烈燄之球"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_MAGE]["寒冰屏障"] = {"buff", nil, {["live"] = 1, ["spell"] = {"低温", 30}}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_MAGE]["法力護盾"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_MAGE]["法師結界"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_MAGE]["幻鏡之像"] = {"持續%t", nil, {["live"] = 1,["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_MAGE]["秘法衝擊"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_MAGE]["冰寒脈動"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_MAGE]["寒冰護體"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_MAGE]["秘法強化"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_MAGE]["衝擊波"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_MAGE]["龍之吐息"] = {"持續%t", nil, {["live"] = 1,["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_MAGE]["冰霜新星"] = {"持續%t", nil, {["live"] = 1,["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_MAGE]["減速術"] = {"debuff", nil, {["unique"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_MAGE]["極度冰凍"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_MAGE]["活體爆彈"] = {"debuff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_MAGE]["燃火"] = {"debuff"};

	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DEATHKNIGHT] = {};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DEATHKNIGHT]["冰錮堅韌"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DEATHKNIGHT]["反魔法護罩"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DEATHKNIGHT]["骸骨之盾"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DEATHKNIGHT]["血族之裔"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DEATHKNIGHT]["冰霜之柱"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DEATHKNIGHT]["巫妖之軀"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DEATHKNIGHT]["邪惡狂熱"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DEATHKNIGHT]["冰霜熱疫"] = {"debuff", nil, {["unique"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DEATHKNIGHT]["血魄瘟疫"] = {"debuff", nil, {["unique"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DEATHKNIGHT]["黑死瘟疫"] = {"debuff", nil, {["unique"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DEATHKNIGHT]["噬溫酷寒"] = {"持續%t", nil, {["live"] = 1,["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DEATHKNIGHT]["絞殺"]   = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DEATHKNIGHT]["亡域打擊"]   = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DEATHKNIGHT]["反魔法力場"] = {"持續%t", nil, {["live"] = 1,["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DEATHKNIGHT]["召喚石像鬼"] = {"持續%t", nil, {["live"] = 1,["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DEATHKNIGHT]["死亡之握"]   = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DEATHKNIGHT]["黑暗幻象"]   = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DEATHKNIGHT]["冰結之觸"]   = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DEATHKNIGHT]["穢邪荒疫"]   = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DEATHKNIGHT]["冰鍊術"]   = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DEATHKNIGHT]["亡域意志"] = {"buff", nil, {["live"] = 1, ["spell"] = {"亡域意志 CD", 45}}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DEATHKNIGHT]["亡靈大軍"] = {"buff", nil, {["live"] = 1, ["spell"] = {"亡靈军团", 45}}};
else
	SPELL_TIMER_TITLE = "SpellTimer";
	SPELL_TIMER_TEXT_OPTION_SLIDER = "You can add some time on this spell .";
	SPELL_TIMER_SHOW_NAME = "Show spell name";
	SPELL_TIMER_SHOW_PROGRESS = "Show Progress bar";

	SPELL_TIMER_POISON = "Poison";

	SPELL_TIMER_TRAP_PATTERN1 = "(.-) effect";
	SPELL_TIMER_TRAP_PATTERN2 = "(.-) aura$";

	SPELL_TIMER_TOTEM_PATTERN = "Totem";

	SPELL_TIMER_TOTEM_TIP = "Right click to cancel totem.";

	SPELL_TIMER_UNITFRAME_TOOLTIP = "Click the lock unlock/lock the window";

	SPELLTIMER_HOUR_WORD = " hour";
	SPELLTIMER_MINUTE_WORD = " min";
	SPELLTIMER_SECOND_WORD = " sec";

	SPELLTIMER_COOLDOWN_INFO = "%s remains %s.";

	SPELL_TIMER_PATTERN_TABLE = {};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARLOCK] = {};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARLOCK]["Fear"] = {"up to %t"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARLOCK]["Immolate"] = {"over %t"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARLOCK]["Banish"] = {"up to %t"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARLOCK]["Corruption"] = {"debuff", {"Seed of Corruption"}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARLOCK]["Seed of Corruption"] = {"over %t", {"Corruption"}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARLOCK]["Siphon Life"] = {"Lasts %t"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARLOCK]["Curse of Doom"] = {"after %t", {"Curse of Agony", "Curse of the Elements", "Curse of Weakness", "Curse of Tongues", "Curse of Recklessness", "Curse of Shado", "Curse of Exhaustion"}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARLOCK]["Curse of Agony"] = {"over %t", {"Curse of Doom", "Curse of the Elements", "Curse of Weakness", "Curse of Tongues", "Curse of Recklessness", "Curse of Shado", "Curse of Exhaustion"}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARLOCK]["Curse of the Elements"] = {"target for %t", {"Curse of Agony", "Curse of Doom", "Curse of Weakness", "Curse of Tongues", "Curse of Recklessness", "Curse of Shado", "Curse of Exhaustion"}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARLOCK]["Curse of Weakness"] = {"for %t.", {"Curse of Agony", "Curse of Doom", "Curse of the Elements", "Curse of Tongues", "Curse of Recklessness", "Curse of Shado", "Curse of Exhaustion"}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARLOCK]["Curse of Tongues"] = {"Lasts %t.", {"Curse of Agony", "Curse of Doom", "Curse of the Elements", "Curse of Weakness", "Curse of Recklessness", "Curse of Shado", "Curse of Exhaustion"}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARLOCK]["Curse of Recklessness"] = {"for %t.", {"Curse of Agony", "Curse of Doom", "Curse of the Elements", "Curse of Weakness", "Curse of Tongues", "Curse of Shado", "Curse of Exhaustion"}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARLOCK]["Curse of Shadow"] = {"for %t", {"Curse of Agony", "Curse of Doom", "Curse of the Elements", "Curse of Weakness", "Curse of Tongues", "Curse of Recklessness", "Curse of Exhaustion"}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARLOCK]["Curse of Exhaustion"] = {"for %t", {"Curse of Agony", "Curse of Doom", "Curse of the Elements", "Curse of Weakness", "Curse of Tongues", "Curse of Recklessness", "Curse of Shado"}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARLOCK]["Death Coil"] = {"for %t"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARLOCK]["Howl of Terror"] = {"for %t", nil, {["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARLOCK]["Enslave Demon"] = {"up to %t"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARLOCK]["Unstable Affliction"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARLOCK]["Haunt"] = {"debuff"};

	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_ROGUE] = {};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_ROGUE][SPELL_TIMER_POISON] = {};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_ROGUE]["Gouge"] = {"for %t"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_ROGUE]["Garrote"] = {"over %t"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_ROGUE]["Sap"] = {"debuff", nil, {["live"] = 1, ["unique"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_ROGUE]["Expose Armor"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_ROGUE]["Cheap Shot"] = {"for %t"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_ROGUE]["Blind"] = {"up to %t"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_ROGUE]["Rupture"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_ROGUE]["Slice and Dice"] = {"buff", nil, {["notarget"] = 1, ["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_ROGUE]["Kick"] = {"for %t"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_ROGUE]["Distract"] = {"for %t"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_ROGUE]["Riposte"] = {"for %t"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_ROGUE]["Kidney Shot"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_ROGUE]["Hunger For Blood"] = {"buff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_ROGUE]["Shadow Dance"] = {"buff"};

	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PRIEST] = {};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PRIEST]["Shadow Word: Pain"] = {"over %t"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PRIEST]["Silence"] = {"for %t"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PRIEST]["Psychic Scream"] = {"for %t", nil, {["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PRIEST]["Vampiric Embrace"] = {"for %t"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PRIEST]["Renew"] = {"over %t"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PRIEST]["Shackle Undead"] = {"up to %t"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PRIEST]["Devouring Plague"] = {"over %t"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PRIEST]["Mind Control"] = {"up to %t"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PRIEST]["Holy Fire"] = {"over %t"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PRIEST]["Mind Soothe"] = {"Lasts %t"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PRIEST]["Vampiric Touch"] = {"over %t"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PRIEST]["Starshards"] = {"over %t"};

	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARRIOR] = {};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARRIOR]["Hamstring"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARRIOR]["Rend"] = {"over %t"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARRIOR]["Shield Bash"] = {"cast for %t"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARRIOR]["Demoralizing Shout"] = {"for %t"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARRIOR]["Piercing Howl"] = {"for %t"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARRIOR]["Mocking Blow"] = {"for %t"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARRIOR]["Thunder Clap"] = {"for %t"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARRIOR]["Disarm"] = {"for %t"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARRIOR]["Intimidating Shout"] = {"Lasts %t"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARRIOR]["Sunder Armor"] = {"Lasts %t"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARRIOR]["Mortal Strike"] = {"for %t"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARRIOR]["Intercept"] = {"for %t"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_WARRIOR]["Rampage"] = {"Lasts %t", nil, {["notarget"] = 1, ["live"] = 1}};

	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_HUNTER] = {};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_HUNTER]["Flare"] = {"for %t"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_HUNTER]["Wing Clip"] = {"for %t"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_HUNTER]["Scare Beast"] = {"up to %t"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_HUNTER]["Counterattack"] = {"for %t"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_HUNTER]["Mend Pet"] = {"over %t"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_HUNTER]["Bestial Wrath"] = {"for %t"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_HUNTER]["Serpent Sting"] = {"debuff", {"Viper Sting", "Scorpid Sting", "Wyvern Sting"}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_HUNTER]["Viper Sting"] = {"debuff", {"Serpent Sting", "Scorpid Sting", "Wyvern Sting"}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_HUNTER]["Scorpid Sting"] = {"debuff", {"Serpent Sting", "Viper Sting", "Wyvern Sting"}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_HUNTER]["Wyvern Sting"] = {"debuff", {"Serpent Sting", "Viper Sting", "Scorpid Sting"}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_HUNTER]["Concussive Shot"] = {"for %t"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_HUNTER]["Scatter Shot"] = {"for %t"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_HUNTER]["Freezing Trap"] = {{"SpellTimer_TrapSearchFunc", {"preventing all action for up to %t", "exist for %t"}, "SpellTimer_TrapActiveFunc"}, nil, nil, {"Frost Trap", "Immolation Tra", "Explosive Trap", "Snake Trap"}, {["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_HUNTER]["Frost Trap"] = {{"SpellTimer_TrapSearchFunc", {"around itself for %t", "exist for %t"}, "SpellTimer_TrapActiveFunc"}, {"Freezing Trap", "Immolation Trap", "Explosive Trap", "Snake Trap"}, {["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_HUNTER]["Immolation Trap"] = {{"SpellTimer_TrapSearchFunc", {"damage over %t", "exist for %t"}, "SpellTimer_TrapActiveFunc"}, {"Freezing Trap", "Frost Trap", "Explosive Trap", "Snake Trap"}, {["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_HUNTER]["Explosive Trap"] = {{"SpellTimer_TrapSearchFunc", {"damage over %t", "exist for %t"}, "SpellTimer_TrapActiveFunc"}, {"Freezing Trap", "Frost Trap", "Immolation Trap", "Snake Trap"}, {["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_HUNTER]["Snake Trap"] = {{"SpellTimer_TrapSearchFunc", {"after %t", "exist for %t"}, "SpellTimer_TrapActiveFunc"}, {"Freezing Trap", "Frost Trap", "Immolation Trap", "Explosive Trap"}, {["notarget"] = 1}};

	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID] = {};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["Hibernate"] = {"up to %t"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["Moonfire"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["Bash"] = {"for %t"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["Demoralizing Roar"] = {"Lasts %t"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["Faerie Fire"] = {"for %t"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["Faerie Fire"] = {"for %t"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["Entangling Roots"] = {"over %t"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["Pounce"] = {"for %t"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["Pounce Bleed"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["Rip"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["Regrowth"] = {"over %t", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["Rejuvenation"] = {"over %t", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["Rake"] = {"over %t"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["Feral Charge"] = {"for %t"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["Insect Swarm"] = {"over %t"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["Bash"] = {"for %t"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["Force of Nature"] = {"for %t"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["Mangle - Bear"] = {"effects for %t"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["Mangle - Cat"] = {"effects for %t"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["Lacerate"] = {"over %t"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["Lifebloom"] = {"over %t"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["Maim"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["Savage Roar"] = {"buff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["Cyclone"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DRUID]["Eclipse"] = {"buff", nil, {["live"] = 1, ["spell"] = {"Eclipse CD", 30}}};

	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_SHAMAN] = {};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_SHAMAN]["Stormstrike"] = {"Lasts %t"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_SHAMAN]["Maelstrom Weapon"] = {"buff", nil, {["live"] = 1}};

	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PALADIN] = {};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PALADIN]["Hammer of Justice	"] = {"for %t"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PALADIN]["Repentance"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PALADIN]["Turn Undead"] = {"up to %t"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PALADIN]["Divine Illumination"] = {"for %t", nil, {["notarget"] = 1, ["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PALADIN]["Light's Grace"] = {"lasts %t", nil, {["notarget"] = 1, ["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PALADIN]["Beacon of Light"] = {"buff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_PALADIN]["Righteous Vengeance"] = {"debuff"};

	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_MAGE] = {};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_MAGE]["Polymorph"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_MAGE]["Cone of Cold"] = {"for %t", {"Frostbolt"}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_MAGE]["Frostbolt"] = {"for %t", {"Cone of Cold"}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_MAGE]["Pyroblast"] = {"over %t"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_MAGE]["Fireball"] = {"over %t"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_MAGE]["Flamestrike"] = {"over %t", nil, {["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_MAGE]["Detect Magic"] = {"for %t"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_MAGE]["Blast Wave"] = {"for %t", nil, {["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_MAGE]["Frost Nova"] = {"for %t", nil, {["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_MAGE]["Summon Water Elemental"] = {"for %t", nil, {["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_MAGE]["Slow"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_MAGE]["Living Bomb"] = {"debuff", nil, {["live"] = 1, ["unique"] = 1}};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_MAGE]["Improved Scorch"] = {"debuff"};

	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DEATHKNIGHT] = {};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DEATHKNIGHT]["Frost Fever"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DEATHKNIGHT]["Blood Plague"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE[BF_CLASS_DEATHKNIGHT]["Ebon Plague"] = {"debuff"};
end