local L = LibStub("AceLocale-3.0"):NewLocale("TotemTimers_GUI", "enUS", true, true)

L["Air"] = true
L["Automatic"] = true
L["Bottom"] = true
L["Cast Button 1"] = true
L["Cast Button 2"] = true
L["Down"] = true
L["Earth"] = true
L["Enable"] = true
L["Fire"] = true
L["Left"] = true
L["none"] = true
L["Right"] = true
L["Top"] = true
L["Totems"] = true
L["TotemTimers"] = true
L["Up"] = true
L["Version"] = true
L["vertical"] = true
L["Water"] = true

L["Blizz Style"] = true
L["Displays timer bars underneath times"] = true
L["General"] = true
L["Hide Blizzard Timers"] = true
L["Hide Default Totem Bar"] = true
L["Hide Default Totem Bar Desc"] = "If you uncheck this you should reload your interface."
L["Hide In Vehicles"] = true
L["Hide In Vehicles Desc"] = "Hides TotemTimers while driving a vehicle. Do not change this setting while driving"
L["Lock"] = true
L["Locks the position of TotemTimers"] = true
L["Red Flash Color"] = true
L["RedFlash Desc"] = "If enabled expiring timers flash red, else they will fade in and out."
L["Shows tooltips on timer and totem buttons"] = true
L["Show Timer Bars"] = true
L["Show Tooltips"] = true
L["Stop Pulse"] = true
L["Stop Pulse Desc"] = " \"If a timer stops its icon gives a big visible pulse\""
L["Time Font"] = true

L["Advanced Options"] = true
L["Arrangement"] = true
L["box"] = true
L["Button Size"] = true
L["Enable Pulse Bar"] = true
L["horizontal"] = true
L["loose"] = true
L["Mini Icons Desc"] = "Shows the small icons in the lower right of the timer buttons which indicate the totem assigned to the active multicast spell and the timer  button will cast."
L["Open On Rightclick"] = true
L["Player Range"] = true
L["Player Range Desc"] = "Shows a red dot on a totem timer if player is out of range"
L["Pulse desc"] = "Shows a green status bar inside the timers that fills until a totem pulses."
L["Raid Member Range"] = true
L["Raid Range Tooltip"] = true
L["Range Desc"] = "Shows how many raid members do not get the buff of your totem in the lower left corner"
L["Rightclick Desc"] = "Open the totem menus on a rightclick instead of hovering over the timer button. Totems can then be dismissed with the middle mouse button instead of a rightclick."
L["RR Tooltip Desc"] = "Shows a list of raid members not in range of your totem on mouseover"
L["Scales the timer buttons"] = true
L["Scaling"] = true
L["Sets the font size of time strings"] = true
L["Sets the format in which times are displayed"] = true
L["Sets the space between timer buttons"] = true
L["Sets the space between timer buttons and timer bars"] = true
L["Sets the width of timer bars."] = true
L["Show Mini Icons"] = true
L["Show Totem Cooldowns"] = true
L["Spacing"] = true
L["Timer Bar Position"] = true
L["Timer Bar Position Desc"] = "Sets at which side of the timer icons the times are displayed"
L["Timers"] = true
L["Time Size"] = true

L["Ankh Tracker"] = true
L["Ankh Tracker Desc"] = "Shows the remaining cooldown of your reincarnation ability as well as the number of ankhs in your bags. Also is used to save and load totem sets."
L["Button 4"] = true
L["EarthShieldDesc"] = "Shows the remaining Earth Shield time and charges. Can be used to cast Earth Shield."
L["Earth Shield Tracker"] = true
L["esrecast"] = "recast (last target/RaidTotems)"
L["Leftclick"] = true
L["Middle Button"] = true
L["Rightclick"] = true
L["Shield Tracker"] = true
L["Trackers"] = true
L["Weapon Buff Tracker"] = true
L["WeaponDesc"] = "Shows the remaining time of your weapon buffs. Leftclick cast the selected weapon buff, rightclick opens a menu to select a buff. I an icon shows two buffs, the first leftclick cast the left buff and a second leftclick the right buff."

L["Color"] = true
L["disabled warnings desc"] = "Even if a tracker is disabled, its warnings of expired buffs will still be shown"
L["EarthShield warnings"] = true
L["Maelstrom notification"] = true
L["Messages"] = true
L["Shield expiration warnings"] = true
L["Show warnings of disabled trackers"] = true
L["Sound"] = true
L["Totem Desctruction Desc"] = "Warning if a totem is destroyed before it is expired."
L["Totem Destruction Message"] = true
L["Totem Expiration Desc"] = "Warning after a totem expires."
L["Totem Expiration Message"] = true
L["Totem Expiration Warning"] = true
L["Totem Warning Desc"] = "Warns 10 secs before a totem expires."
L["Warnings"] = true
L["Weapon buff warnings"] = true

L["Menu Direction"] = true
L["Multicast Button"] = true
L["Same as totem menus"] = true

L["Duration"] = true
L["ECD Button Size"] = true
L["ECD Font Size"] = true
L["EnhanceCDs"] = true
L["Hide OOC Desc"] = "Changing this setting will have effect after the next combat"
L["Hide out of combat"] = true
L["Maelstrom Bar Height"] = true
L["OOC Alpha"] = true
L["OOC Alpha Desc"] = "Controls the opacity of the buttons out of combat, 0 = transparent, 1 = opaque"
L["Show OmniCC counters"] = true

TT_GUI_ROLE_NAMES = {
    [0]="uninspected",
    [1]="melee",
    [2]="ranged",
    [3]="caster",
    [4]="healer",
    [5]="enhancer"
}

