local L = LibStub("AceLocale-3.0"):NewLocale("Cartographer_QuestInfo", "zhTW");

if (L) then
-- Core.lua
	L["Enabled"] = "開啟";
	L["Suspend/resume this module."] = "開啟活關閉任務查詢";
	L["Icon alpha"] = "圖示透明度";
	L["Alpha transparency of the icon."] = "地圖上的圖示透明度。";
	L["Icon size"] = "圖示大小";
	L["Size of the icons on the map."] = "地圖上的圖示大小。";
	L["Show minimap icons"] = "在小地圖上顯示";
	L["Show quest icons on the minimap."] = "在小地圖上顯示任務圖示。";
	L["Show all quest givers"] = "顯示所有任務委託人";
	L["Show all quest givers, or just show givers around your level."] = "顯示所有任務委託人，不然只限於接近你等級的任務。";
	L["Include giver's quest list"] = "顯示任務委託人的任務清單";
	L["Include quest list when showing quest givers, or just show the number of quests (which is much faster)."] = "顯示任務委託人的任務清單，不然只顯示可接任務的數量(速度較快)。";
	L["Show world map button"] = "顯示'任務資訊'按鈕";
	L["Show button on the world map."] = "在世界地圖上顯示'任務資訊'的設定按鈕。";
	L["Show quest level"] = "顯示任務等級";
	L["Show quest level in quest log and NPC dialog."] = "在任務視窗及對話框顯示任務等級。";
	L["Make quest log double wide"] = "加寬任務視窗";
	L["Make the quest log window double wide, this will require UI reload."] = "加寬顯示任務視窗，注意:這功能需要重載UI後才能改變。";
	L["Auto update quest icons"] = "自動更新任務圖示";
	L["Auto update quest icons after quest or objective completed."] = "當任務或任務目標變動時，自動更新任務圖示。";
	L["Update tracked quests only"] = "只更新已追蹤任務";
	L["Update tracked quests only, or update all active quests."] = "只更新已追蹤任務，不然更新全部進行中任務。";
	L["Quest Info"] = "任務資訊";
	L["Module description"] = "提供任務資料";
	L["GROUP"] = "團體";

-- LocationFrame.lua
	L["Close"] = "關閉";

-- Map.lua
	L["Quest Start"] = "任務開始";
	L["Quest End"] = "任務結束";
	L["Quest Giver"] = "任務委託人";
	L["Quest Objective"] = "任務目標";
	L["Show active quests"] = "標示進行中任務";
	L["Show all info of active quests on current map."] = "在目前地圖上標示進行中的任務目標。";
	L["Show tracked quests"] = "標示已追蹤任務";
	L["Show all info of tracked quests on current map."] = "在目前地圖上標示已追蹤的任務目標。";
	L["Show available quests"] = "標示可接的任務";
	L["Show the givers of available quests on current map."] = "在目前地圖上標示可接的任務委託人。";
	L["Clear quest icons"] = "清除任務圖示";
	L["Clear quest icons generated by QuestInfo."] = "清除由任務資訊所產生的圖示。";
	L["Open QuestInfo menu"] = "開啟任務資訊選項";
	L["Alt-Click: "] = "Alt-點擊: ";
	L["Shift-Click: "] = "Shift-點擊: ";
	L["Elite"] = "精英";
	L["Rare Elite"] = "稀有精英";
	L["Boss"] = "首領";
	L["Name:"] = "名稱:";
	L["Objective:"] = "目標:";
	L["Source:"] = "來源:";
	L["Level:"] = "等級:";
	L["Location:"] = "座標:";
	L["Quests:"] = "任務:";
	L["%d Quests"] = "%d個任務";

-- QuestFuPatch.lua
	L["(done)"] = "(完成)";

-- QuestLogPatch.lua
	L[" ..."] = " …";
	L["... more"] = "… 還有更多";

-- SeriesFrame.lua
	L["Quest Series"] = "系列任務";
	L["Requires:"] = "需要等級:";
	L["Sharable"] = "可分享";
	L["Series:"] = "任務系列:";

	-- Notes
	L["Notes"] = "標注"
	L["Module which allows you to put notes on the map.\n\nHint: /note is available to create notes with the command line."] = "允許你在大地圖上定義標注.\n\n提示: 輸入/note快捷創建一個標注"
	L["Icon size"] = "圖示尺寸"
	L["Size of the icons on the map"] = "調整圖示在地圖上顯示的尺寸"
	L["Show minimap icons"] = "在小地圖上顯示標記(開發中)"
	L["Show icons on the minimap"] = "在小地圖上顯示標記"
	L["Minimap icon size"] = "小地圖標記尺寸"
	L["Size of the icons on the minimap"] = "調整在小地圖上的標記尺寸"
	L["Clear all notes on map"] = "清除地圖上所有的標注資料"
	L["This will clear all notes on map"] = "將清除地圖上的所有標注資料"
	L["Enable Notes"] = "啟用標注"

	L["Can't create a note for your current position"] = "無法標記你當前位置"
	L["Create a note success"] = "在當前位置新增一個標記."
	L["Create a new note"] = "創建一個新的標注"
	L["New note"] = "新標注"
	L['Okay'] = "確定"
	L['Cancel'] = "取消"
	L['White'] = "白色"
	L['Gray'] = "灰色"
	L['Pink'] = "粉紅色"
	L['Red'] = "紅色"
	L['Orange'] = "橙色"
	L['Yellow'] = "黃色"
	L['Green'] = "綠色"
	L['Stone grey'] = "石灰色"
	L['Cyan'] = "青色"
	L['Blue'] = "藍色"
	L['Sky-blue'] = "淡藍色"
	L['Purple'] = "紫色"
	L["X Offset"] = "x 座標"
	L["Y Offset"] = "y 座標"
	L["Zone"] = "區域"
	L["Title"] = "標題"
	L["Info1"] = "信息行1(可選)"
	L["Info2"] =  "信息行2(可選)"
	L["Creator"] = "創建者(可選)"
	L["Custom Icon"] = "定制圖示"
	L["New Note"] = "新標注"
	L["Edit note"] = "編輯標注"
	L['Range'] = "距離"
	L["Creator: "] = "創建: "
	L['Delete note'] = "刪除標記"
	L["Send"] = "發送"
	L["Send to Party/Raid"] = "發送到隊伍/團隊"
	L["Send to guild"] = "發送到公會"
	L["Send to player"] = "發送給玩家"
	L[" at "] = "在 "
	L["Right-Click on map to zoom out"] = "右鍵點擊世界地圖放大"
	L["Left-Click on map to zoom in"] = "左鍵點擊世界地圖縮小"
	L["Ctrl-Right-Click on map to add a note"] = "ctrl-右鍵點擊世界地圖創建一個標記"

	L["Portal"] = "傳送門"

	L["Aldor FlightMaster"] = "奧多爾飛行管理員"
	L["Alliance FlightMaster"] = "聯盟飛行管理員"
	L["Create waypoint"] = "建立路徑點"
	L["Druid FlightMaster"] = "德魯伊飛行管理員"
	L["FlightMaster Icons"] = "飛行管理員圖示"
	L["FlightMasters"] = "飛行管理員"
	L["Flight path lines"] = "飛行路線"
	L["HandyNotes - FlightMasters"] = "HandyNotes - FlightMasters"
	L["Horde FlightMaster"] = "部落飛行管理員"
	L["Icon Alpha"] = "圖示透明度"
	L["Icon Scale"] = "圖示比例"
	L["Neutral FlightMaster"] = "中立飛行管理員"
	L["PvP FlightMaster"] = "PvP飛行管理員"
	L["Scryer FlightMaster"] = "占卜者飛行管理員"
	L["Show all flightmasters instead of only those that you can use"] = "顯示所有飛行管理員而不只是顯示你能使用的"
	L["Show both factions"] = "顯示雙方陣營"
	L["Show flightmasters on continent level maps as well"] = "在大陸地圖上也顯示飛行路線"
	L["Show flight path lines"] = "顯示飛行路線"
	L["Show flight path lines on the world map"] = "在世界地圖上顯示飛行路線"
	L["Show flight path lines on the zone maps as well"] = "在區域地圖中也顯示飛行路線"
	L["Show in zones"] = "在地區中顯示"
	L["Show on continent maps"] = "在大陸地圖上顯示"
	L["Skyguard FlightMaster"] = "禦天者飛行管理員"
	L["The alpha transparency of the icons"] = "圖示的透明程度"
	L["The scale of the icons"] = "圖示的比例"
	L["These settings control the look and feel of the FlightMaster icons."] = "這些設定控制飛行管理員圖示的外觀和風格。"
end
