-- local L = Rock("LibRockLocale-1.0"):GetTranslationNamespace("Cartographer_QuestInfo")
local L = LibStub("AceLocale-3.0"):NewLocale("Cartographer_QuestInfo", "zhCN");

if (L) then
-- Core.lua
	L["Enabled"] = "开启";
	L["Suspend/resume this module."] = "开启或关闭任务查询";
	L["Icon alpha"] = "图示透明度";
	L["Alpha transparency of the icon."] = "地图上的图示透明度。";
	L["Icon size"] = "图示大小";
	L["Size of the icons on the map."] = "地图上的图示大小。";
	L["Show minimap icons"] = "在小地图上显示";
	L["Show quest icons on the minimap."] = "在小地图上显示任务图标。";
	L["Show all quest givers"] = "显示所有任务委托人";
	L["Show all quest givers, or just show givers around your level."] = "显示所有任务委托人，不然只限于接近你等级的任务。";
	L["Include giver's quest list"] = "显示任务委托人的任务列表";
	L["Include quest list when showing quest givers, or just show the number of quests (which is much faster)."] = "显示任务委托人的任务列表，不然只显示可接任务的数量(速度较快)。";
	L["Show world map button"] = "显示'任务信息'按钮";
	L["Show button on the world map."] = "在世界地图上显示'任务信息'的设定按钮。";
	L["Show quest level"] = "显示任务等级";
	L["Show quest level in quest log and NPC dialog."] = "在任务窗口及对话框显示任务等级。";
	L["Make quest log double wide"] = "加宽任务窗口";
	L["Make the quest log window double wide, this will require UI reload."] = "加宽显示任务窗口，注意:这功能需要重载UI后才能改变。";
	L["Auto update quest icons"] = "自动更新任务图标";
	L["Auto update quest icons after quest or objective completed."] = "当任务或任务目标变动时，自动更新任务图标。";
	L["Update tracked quests only"] = "只更新已追踪任务";
	L["Update tracked quests only, or update all active quests."] = "只更新已追踪任务，不然更新全部进行中任务。";
	L["Quest Info"] = "任务信息";
	L["Module description"] = "提供任务数据";
	L["GROUP"] = "团体";

-- LocationFrame.lua
	L["Close"] = "关闭";

-- Map.lua
	L["Quest Start"] = "任务开始";
	L["Quest End"] = "任务结束";
	L["Quest Giver"] = "任务委托人";
	L["Quest Objective"] = "任务目标";
	L["Show active quests"] = "标示进行中任务";
	L["Show all info of active quests on current map."] = "在目前地图上标示进行中的任务目标。";
	L["Show tracked quests"] = "标示已追踪任务";
	L["Show all info of tracked quests on current map."] = "在目前地图上标示已追踪的任务目标。";
	L["Show available quests"] = "标示可接的任务";
	L["Show the givers of available quests on current map."] = "在目前地图上标示可接的任务委托人。";
	L["Clear quest icons"] = "清除任务图标";
	L["Clear quest icons generated by QuestInfo."] = "清除由任务信息所产生的图标。";
	L["Open QuestInfo menu"] = "开启任务信息选项";
	L["Alt-Click: "] = "Alt-点击: ";
	L["Shift-Click: "] = "Shift-点击: ";
	L["Elite"] = "精英";
	L["Rare Elite"] = "稀有精英";
	L["Boss"] = "首领";
	L["Name:"] = "名称:";
	L["Objective:"] = "目标:";
	L["Source:"] = "来源:";
	L["Level:"] = "等级:";
	L["Location:"] = "坐标:";
	L["Quests:"] = "任务:";
	L["%d Quests"] = "%d个任务";

-- QuestFuPatch.lua
	L["(done)"] = "(完成)";

-- QuestLogPatch.lua
	L[" ..."] = " …";
	L["... more"] = "… 还有更多";

-- SeriesFrame.lua
	L["Quest Series"] = "系列任务";
	L["Requires:"] = "需要等级:";
	L["Sharable"] = "可分享";
	L["Series:"] = "任务系列:";

	-- Notes
	L["Notes"] = "标注"
	L["Module which allows you to put notes on the map.\n\nHint: /note is available to create notes with the command line."] = "允许你在大地图上定义标注.\n\n提示: 输入/note快捷创建一个标注"
	L["Icon size"] = "图标尺寸"
	L["Size of the icons on the map"] = "调整图标在地图上显示的尺寸"
	L["Show minimap icons"] = "在小地图上显示标记(开发中)"
	L["Show icons on the minimap"] = "在小地图上显示标记"
	L["Minimap icon size"] = "小地图标记尺寸"
	L["Size of the icons on the minimap"] = "调整在小地图上的标记尺寸"
	L["Clear all notes on map"] = "清除地图上所有的标注数据"
	L["This will clear all notes on map"] = "将清除地图上的所有标注数据"
	L["Enable Notes"] = "启用标注"

	L["Can't create a note for your current position"] = "无法标记你当前位置"
	L["Create a note success"] = "在当前位置新增一个标记."
	L["Create a new note"] = "创建一个新的标注"
	L["New note"] = "新标注"
	L['Okay'] = "确定"
	L['Cancel'] = "取消"
	L['White'] = "白色"
	L['Gray'] = "灰色"
	L['Pink'] = "粉红色"
	L['Red'] = "红色"
	L['Orange'] = "橙色"
	L['Yellow'] = "黄色"
	L['Green'] = "绿色"
	L['Stone grey'] = "石灰色"
	L['Cyan'] = "青色"
	L['Blue'] = "蓝色"
	L['Sky-blue'] = "淡蓝色"
	L['Purple'] = "紫色"
	L["X Offset"] = "x 坐标"
	L["Y Offset"] = "y 坐标"
	L["Zone"] = "区域"
	L["Title"] = "标题"
	L["Info1"] = "信息行1(可选)"
	L["Info2"] =  "信息行2(可选)"
	L["Creator"] = "创建者(可选)"
	L["Custom Icon"] = "定制图标"
	L["New Note"] = "新标注"
	L["Edit note"] = "编辑标注"
	L['Range'] = "距离"
	L["Creator: "] = "创建: "
	L['Delete note'] = "删除标记"
	L["Send"] = "发送"
	L["Send to Party/Raid"] = "发送到队伍/团队"
	L["Send to guild"] = "发送到公会"
	L["Send to player"] = "发送给玩家"
	L[" at "] = "在 "
	L["Right-Click on map to zoom out"] = "右键点击世界地图放大"
	L["Left-Click on map to zoom in"] = "左键点击世界地图缩小"
	L["Ctrl-Right-Click on map to add a note"] = "ctrl-右键点击世界地图创建一个标记"
	L["General Settings"] = "综合设定"
	L["Show note creator"] = "显示标注创建者"
end
