-- Chinese localization file for zhTW.
local AceLocale = LibStub:GetLibrary("AceLocale-3.0")
local zhTW = AceLocale:NewLocale("YssBossLoot", "zhTW")
if not zhTW then return end

zhTW["Show Boss Frame"] ="顯示首領框架"
zhTW["2D Skulls"] = "2D骷髏"
zhTW["3D_Skull_Detect_MSG"] = "|cffffd200YssBossLoot檢測到%s!|r|n|n你要將你的首領框架設定為3D骷髏嗎?"
zhTW["Add Tooltip Info"] = "新增提示訊息資訊"
zhTW["Animated Background"] = "動態背景"
zhTW["Boss Font Size"] = "首領字型大小"
zhTW["Boss Frame Size"] = "首領框架大小"
zhTW["|cFFFF0000<<WARNING>>|r|nIf you change these from the default grey checkmark you may missout on items with no stats.|nOnly item stats you have previously seen can be filtered by default"] = "|cFFFF0000<<警告>>|r|n如果你變更了預設的灰色複選標記那麼你可能會看不見沒有此能力值的物品。|n預設值為只有你先前見過的物品能力值才可篩選"
zhTW["|cffffff00Click|r to open YssBossLoot Options"] = "|cffffff00點擊|r後開啟YssBossLoot選項"
zhTW["|cffffff00Click|r to toggle YssBossLoot"] = "|cffffff00點擊後|r切換YssBossLoot"
zhTW["|cffffff00Left Click|r to select Instance"] = "|cffffff00左鍵點擊|r後選擇副本"
zhTW["|cffffff00Right Click|r to open Options"] = "|cffffff00右鍵點擊|r後開啟選項"
zhTW["Check All"] = "查看全部"
zhTW["Class Filter"] = "職業篩選"
zhTW["Don't Want:"] = "不需要:"
zhTW["Dungeon"] = "地城"
zhTW["Equip Location Filter"] = "裝備位置篩選"
zhTW["Filter"] = "篩選"
zhTW["Filter All"] = "篩選全部"
zhTW['|cffff2222%s not cached!'] = "|cffff2222%s 暫無數據"
zhTW["Filter All desc"] = [=[由於多重篩選
你很可能必須停用
兩個或多個篩選之後使用
該篩選按鈕。]=]
zhTW["Heroic 10-man Loot"] = "10人英雄模式戰利品"
zhTW["Heroic 25-man Loot"] = "25人英雄模式戰利品"
zhTW["Heroic Loot"] = "英雄模式掉落"
zhTW["Hide Loot"] = "隱藏戰利品"
zhTW["Hides this sub type from being displayed"] = "隱藏子類型被顯示"
zhTW["Instance Type"] = "副本難度"
zhTW["Item Stat Filter"] = "物品能力值篩選"
zhTW["Item Type Filter"] = "物品類型篩選"
zhTW["Large Map"] = "大地圖"
zhTW["Large Map with Objectives"] = "大地圖的具體目標"
zhTW["Loot"] = "戰利品"
zhTW["Loot Scaling"] = "戰利品比例"
zhTW["Minimap Icon"] = "小地圖圖示"
zhTW["No Class Restriction"] = "沒有職業限定"
zhTW["Normal 10-man Loot"] = "10人普通模式戰利品"
zhTW["Normal 25-man Loot"] = "25人普通模式戰利品"
zhTW['Non Boss Drops'] = "小怪掉落"
zhTW["Normal Loot"] = "普通模式戰利品"
zhTW["Only equip location you have previously seen can be filtered by default"] = "預設值為只有你先前見過的裝備位置才能篩選"
zhTW["Only item stats you have previously seen can be filtered by default"] = "預設值為只有你先前見過的物品能力值才可篩選"
zhTW["Only Type/SubType combinations you have previously seen can be filtered by default"] = "預設值為你先前見過的類型/子類型才能篩選"
zhTW["Open to Current Instance Difficulty"] = "開啟當前的副本難度"
zhTW["Open to Currently Selected Difficulty in Group"] = "在團體中開啟當前選定的難度"
zhTW["Open to Currently Selected Difficulty in Group desc"] = "如果你在一個團體裡但依然在地城外面時則開啟當前選定的難度"
zhTW["Raid"] = "團隊"
zhTW["Show All"] = "顯示全部"
zhTW["Show this sub type"] = "顯示此子類型"
zhTW["Small Map"] = "小地圖"
zhTW["Uncheck All"] = "不查看全部"
zhTW["UNSAVE_QUERY_MSG"] = [=[|cFF33FF99YssBossLoot|r已檢測到你剛剛斷線。也許是因為掃瞄太多|cffff2020不安全的物品連結|r所導致，所以才會在掃描時斷線。

|cffffd200你要繼續掃描嗎?|r]=]
zhTW["Use 3D Skull"] = "使用3D骷髏"
zhTW["Want:"] = "需要:"
zhTW["When selected items with this class restriction will be shown"] = "當選定的物品有職業限定時將被顯示"
zhTW["When selected this item equip location will be filtered out"] = "當選定此裝備的部位將會被篩選掉"
zhTW["When selected this item equip location will be shown"] = "當選定此物品的部位時將會被顯示"
zhTW["When selected this item stat will be filtered out"] = "當選定這個物品能力值將被篩選掉"
zhTW["When selected this item type will be hidden unless multible subtypes are found"] = "當選擇此物品類型將會被隱藏，除非子類型被找到"
zhTW["When selected this item type will be shown unless multible subtypes are found"] = "當選定此物品類型時將會被顯示，除非子類型被找到"
zhTW["Yellow Checkmark:|nWe want this stat.|n|nGrey Checkmark:|nWe do not care if we have this stat or not.|n|nNo Checkmark:|nWe do not want this stat."] = "黃色複選標記:|n我需要此能力值。|n|n灰色複選標記:|n不在乎此能力值是否為我需要的。|n|n無複選標記:|n我不需要此能力值。"

